C
      INTEGER*4 IACT,IRESV,IWRITE,INAME,
     *          ICAST,IDATA0,IALL,ISKIP,ISKIP1,ICHECK 
      CHARACTER*30 NAME
      DATA IWRITE / 2 /
      DATA INAME  / 1 /
      DATA ICAST  / 0 /
      DATA IDATA0 / 0 /
      DATA IALL   / 0 /
      DATA ISKIP  / 0 /
      DATA ISKIP1 / 1 /
      DATA ICHECK /999999/
C
      INTEGER*4 MCOMFL,MCOMST,MCOM
      PARAMETER ( MCOMFL = 10000, MCOMST = 10000 )
      CHARACTER*60 CFLEMS(MCOMFL),CFLEBC(MCOMFL),CFLEFF(MCOMFL)
      CHARACTER*60 CSETMS(MCOMST),CSETBC(MCOMST),CSETFF(MCOMST)
      PARAMETER ( MCOM= 10000 )
      CHARACTER*60 COMFLE(MCOM),COMSET(MCOM)
C
      INTEGER*4 NCOMFL,NCOMST
      DATA NCOMFL /0/
      DATA NCOMST /0/
C
      INTEGER*4 LERR(1000)
C
