C
C      HEADDER FILE DEFINIG CONSTANTS AND DECLARING GLOBAL
C     VARIABLES FOR GENERIC GRAPHIC INTERFACE
C                        author: C. Kato, MERL, Hitachi, Ltd.
C                        date written: August 27th, 1992
C
C
C      <<<<< CONSTANTS >>>>>
C
C
C LINE TYPES
C
C
C   SOLID  LINE
      INTEGER*4 GLSOLD
      PARAMETER ( GLSOLD =  1 )
C
C   DASHED LINE
      INTEGER*4 GLDASH
      PARAMETER ( GLDASH =  2 )
C
C
C  LINE WIDTHS
C
C
C   NORMAL WIDTH
      INTEGER*4 GLNORM
      PARAMETER ( GLNORM =  1 )
C
C   BOLD LINE
      INTEGER*4 GLBOLD
      PARAMETER ( GLBOLD =  2 )
C
C
C FONT TYPES
C
C
C  COURIER FAMILY
C
C   COURIER
      INTEGER*4 GCRR
      PARAMETER ( GCRR   =  1 )
C
C   COURIER-BOLD
      INTEGER*4 GCRRB
      PARAMETER ( GCRRB  =  2 )
C
C   COURIER-OBLIQUE
      INTEGER*4 GCRRO
      PARAMETER ( GCRRO  =  3 )
C
C   COURIER-BOLDOBLIQUE
      INTEGER*4 GCRRBO
      PARAMETER ( GCRRBO =  4 )
C
C  HELVETICA FAMILY
C
C   HELVETICA
      INTEGER*4 GHLV
      PARAMETER ( GHLV   =  5 )
C
C   HELVETICA-BOLD
      INTEGER*4 GHLVB
      PARAMETER ( GHLVB  =  6 )
C
C   HELVETICA-OBLIQUE
      INTEGER*4 GHLVO
      PARAMETER ( GHLVO  =  7 )
C
C  HELVETICA-BOLDOBLIQUE
      INTEGER*4 GHLVBO
      PARAMETER ( GHLVBO =  8 )
C
C  TIMES FAMILY
C
C   TIMES-ROMAN
      INTEGER*4 GTMS
      PARAMETER ( GTMS   =  9 )
C
C   TIMES-BOLD
      INTEGER*4 GTMSB
      PARAMETER ( GTMSB  = 10 )
C
C   TIMES-ITALIC
      INTEGER*4 GTMSO
      PARAMETER ( GTMSO  = 11 )
C
C   TIMES-BOLDITALIC
      INTEGER*4 GTMSBO
      PARAMETER ( GTMSBO = 12 )
C
C
C MARKER INDICES
C
C
C  OPEN   CIRCLE
      INTEGER*4 GCIRCL
      PARAMETER ( GCIRCL = 1 )
C
C  FILLED CIRCLE
      INTEGER*4 GCIRCF
      PARAMETER ( GCIRCF = 2 )
C
C  OPEN   SQUARE
      INTEGER*4 GSQUAR
      PARAMETER ( GSQUAR = 3 )
C
C  FILLED SQUARE
      INTEGER*4 GSQUAF
      PARAMETER ( GSQUAF = 4 )
C
C  CROSS
      INTEGER*4 GCROSS
      PARAMETER ( GCROSS = 5 )
C
C
C COLOR INDICES
C
C
C  BLACK
      INTEGER*4 GBLACK
      PARAMETER ( GBLACK = 0 )
C
C  RED
      INTEGER*4 GRED
      PARAMETER ( GRED   = 1 )
C
C  GREEN
      INTEGER*4 GGREEN
      PARAMETER ( GGREEN = 2 )
C
C  YELLOW
      INTEGER*4 GYELOW
      PARAMETER ( GYELOW = 3 )
C
C  BLUE
      INTEGER*4 GBLUE
      PARAMETER ( GBLUE  = 4 )
C
C  MAGENTA
      INTEGER*4 GMAGEN
      PARAMETER ( GMAGEN = 5 )
C
C  CYAN
      INTEGER*4 GCYAN
      PARAMETER ( GCYAN  = 6 )
C
C  WHITE
      INTEGER*4 GWHITE
      PARAMETER ( GWHITE = 7 )
C
C  FOREGROUND COLOR
      INTEGER*4 GFGCOL
      PARAMETER ( GFGCOL = GWHITE )
C
C  BACKGROUND COLOR
      INTEGER*4 GBGCOL
      PARAMETER ( GBGCOL = GBLACK )
C
C
C 
C      <<<<< GLOBAL VARIABLE DECLARATION >>>>>
C
C
C
C  LINE TYPE
      INTEGER*4 LNTYPE, PLTYPE
C
C  LINE WIDTH
      INTEGER*4 LNWDTH, PLWDTH
C
C  TEXT TYPE
      INTEGER*4 TXTYPE, PTTYPE
C
C  TEXT SIZE
      REAL   *4 TXSIZE, PTSIZE
C
C  MARK TYPE
      INTEGER*4 MKTYPE, PMTYPE
C
C  MARK SIZE
      REAL   *4 MKSIZE, PKSIZE
C
      COMMON / GNATRV / LNTYPE, LNWDTH, TXTYPE, TXSIZE, MKTYPE, MKSIZE
      COMMON / PSATRV / PLTYPE, PLWDTH, PTTYPE, PTSIZE, PMTYPE, PKSIZE
C
C      END OF HEADDER FILE
C
