C
      INTEGER*4  MUSRT
      PARAMETER(MUSRT=1000)
      INTEGER*4  LUSRT(MUSRT),NUSRT(MUSRT)
      REAL*8     DTUSRT(MUSRT),TSUSRT(MUSRT),TEUSRT(MUSRT)
      CHARACTER*30 CUSRT(MUSRT)
C
      COMMON /USRT/ DTUSRT,TSUSRT,TEUSRT,LUSRT,NUSRT,CUSRT
C
