      SUBROUTINE CBC126(NG,NP,ILEVEL,IPOSI,F,FBC3)
      IMPLICIT NONE
      INTEGER*4 NG,NP,ILEVEL,IPOSI
      REAL*8    F(0:NG+2,0:NG+2,0:NG+2,NP),FBC3(NP)
      INTEGER*4 I,J,K
C
C     ====FUNCTION====
C     SET B.C. DATA TO F FROM EDGE-TYPE B.C. BUFFER WITH B.C. FLAG-TYPE OF 026
C     NOTE THAT B.C. TYPE IS DEFINED AT SEND-SIDE CUBE
C
C     ====VARIABLES LIST====
C
C[IN]
C     NG            :GRID SIZE (2^N)
C     NP            :NUMBER OF PARTICLES (=15)
C     ILEVEL        :LEVEL (RESOLUTION) OF RECIEVE SIDE CUBE
C     FBC3(II)      :WORK REGION FOR FACE-TYPE  B.C. GROUPS
C
C[OUT]
C     F(I,J,K,IP)   :PARTICLE DISTRIBUTION FUNCTION
C
      IF(ILEVEL.EQ.0 .OR. ILEVEL.EQ.-1 .OR. IPOSI.EQ.1) THEN
          I=NG+2
          J=0
          K=0
          IF(ILEVEL.EQ.-1) I=NG+1
          IF(ILEVEL.EQ.-1) J=1
          IF(ILEVEL.EQ.-1) K=1
          F(I,J,K,1:NP)=FBC3(1:NP)
      ENDIF
      RETURN
      END
