CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                        C
C     LBMPRM                                                             C
C                                                                        C
C            2016.11.29 WRITTEN BY Y.YAMADE                              C
C                                                                        C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE LBMPRM(IUTIN,IUT6,IPART,ISTART,NTIME,
     *                  DSCALE,VSCALE,VISCM,RHO0,IOUT,INTFSV,
     *                  MSAMPL,NSAMPL,LSAMPL, 
     *                  XSAMPL,YSAMPL,ZSAMPL,
     *                  FILECB,FILEBC,FILEIF,FILEFF,FILEVF,
     *                  FILEAV,FILERM,FILEFS,FILEHT,IUT0,IERR)
      IMPLICIT NONE
      INTEGER*4    IUTIN,IUT6,IPART,ISTART,NTIME,IOUT,INTFSV
      REAL*8       DSCALE,VSCALE,VISCM,RHO0
      INTEGER*4    MSAMPL,NSAMPL,LSAMPL(5,MSAMPL) 
      REAL*8       XSAMPL(MSAMPL),YSAMPL(MSAMPL),ZSAMPL(MSAMPL)
      CHARACTER*60 FILECB,FILEBC,FILEIF,FILEVF,
     *             FILEFF,FILEHT,FILEAV,FILERM,FILEFS
      INTEGER*4    IUT0,IERR
C
      CHARACTER*60 FILE
C
C[IN]
C     IUTIN    :UNIT NUMBER OF PARAMETER FILE 
C     IUT6     :UNIT NUMBER OF STANDARD OUTPUT
C
C[OUT]
C     ISTART   :RESTART FLAG (0:OFF, 1:ON)
C     NTIME    :NUMBER OF TIME STEPS 
C     DSCALE LENGTH OF MINIMUMU CUBE
C     VSCALE VELOCITY RATIO BETWEEN CHARACTEERICTIC AND PARTICLE VELOCITY 
C     VISCM  NORMALIZED VISCOCITY BY DSCALE AND VSCALE
C     RHO0   INITIAL DENSITY
C     UINLT  U-VELOCITY AT INLET B.C.       (NORMALIZED BY VSCALE)
C     VINLT  V-VELOCITY AT INLET B.C.       (NORMALIZED BY VSCALE)
C     WINLT  W-VELOCITY AT INLET B.C.       (NORMALIZED BY VSCALE) 
C     UWALL  U-VELOCITY AT MOVING WALL B.C. (NORMALIZED BY VSCALE)
C     VWALL  V-VELOCITY AT MOVING WALL B.C. (NORMALIZED BY VSCALE)
C     WWALL  W-VELOCITY AT MOVING WALL B.C. (NORMALIZED BY VSCALE)
C     FILEIN   :FILE NAME OF PARAMETER        FILE ( INPUT) (=PARAMLBM3D)
C     FILECB   :FILE NAME OF GF-CUBE          FILE ( INPUT)
C     FILEBC   :FILE NAME OF GF-BOUNDARY      FILE ( INPUT)
C     FILEIF   :FILE NAME OF GF-FLOW          FILE ( INPUT)
C     FILEVF   :FILE NAME OF GF-FUNC          FILE (OUTPUT)
C     FILEFF   :FILE NAME OF GF-FLOW          FILE (OUTPUT)
C     FILEHT   :FILE NAME OF GF-HIST          FILE (OUTPUT)
C     FILEAV   :FILE NAME OF GF-FLOW AVE.     FILE (OUTPUT)
C     FILERM   :FILE NAME OF GF-FLOW RMS      FILE (OUTPUT)
C     FILEFS   :FILE NAME OF GF-FLOW UNSTEADY FILE (OUTPUT)
C
      CHARACTER*60 ERRMSG,EREXP1
      DATA ERRMSG
     * / ' ## SUBROUTINE LBMPRM: FATAL      ERROR OCCURENCE; RETURNED' /
      DATA EREXP1
     * / ' FILE FORMAT OF THE  FILE IS NOT FOR FFX   ' /
C
      CHARACTER*15 COMDAT(4)
      DATA COMDAT(1) / ' DEBSITY      ;' /
      DATA COMDAT(2) / ' VELOCITY-U   ;' /
      DATA COMDAT(3) / ' VELOCITY-V   ;' /
      DATA COMDAT(4) / ' VELOCITY-W   ;' /
C
      INTEGER*4 ISAMPL
C
      IERR = 0
C
      READ(IUTIN,*)
      READ(IUTIN,*)
      READ(IUTIN,*)
      READ(IUTIN,*) ISTART,NTIME,IOUT,INTFSV
      READ(IUTIN,*)
      READ(IUTIN,*) DSCALE,VSCALE,VISCM,RHO0
      READ(IUTIN,*)
      READ(IUTIN,*) NSAMPL
      IF(NSAMPL.GT.MSAMPL) THEN
           WRITE(IUT6,*) 'INSUFFICIENT MEMORY SPACE FOR HIST'
           IERR=1
           RETURN 
      ENDIF
C
      DO 1000 ISAMPL=1,NSAMPL
          READ(IUTIN,*) LSAMPL(1,ISAMPL),
     *                  XSAMPL(ISAMPL),YSAMPL(ISAMPL),ZSAMPL(ISAMPL)
 1000 CONTINUE   
C
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILECB
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILEBC
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILEIF
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILEVF
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILEFF
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILEHT
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILEAV
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILERM
      READ(IUTIN,*)
      READ(IUTIN,'(A60)') FILEFS
C
      IF(IPART.GE.1) THEN
          CALL MFNAME(FILECB,FILE,IPART,IUT6,IERR)
          FILECB = FILE
C
          CALL MFNAME(FILEBC,FILE,IPART,IUT6,IERR)
          FILEBC = FILE
C
          CALL MFNAME(FILEIF,FILE,IPART,IUT6,IERR)
          FILEIF = FILE
C
          CALL MFNAME(FILEVF,FILE,IPART,IUT6,IERR)
          FILEVF = FILE
C
          CALL MFNAME(FILEFF,FILE,IPART,IUT6,IERR)
          FILEFF = FILE
C
          CALL MFNAME(FILEHT,FILE,IPART,IUT6,IERR)
          FILEHT = FILE
C
          CALL MFNAME(FILEAV,FILE,IPART,IUT6,IERR)
          FILEAV = FILE
C
          CALL MFNAME(FILERM,FILE,IPART,IUT6,IERR)
          FILERM = FILE
C
          CALL MFNAME(FILEFS,FILE,IPART,IUT6,IERR)
          FILEFS = FILE
      ENDIF 
C
CCYYTMP---
      IF(IOUT.NE.0) THEN
          WRITE(IUT6,*) 'IOUT OF 1,2 IS NOT SUPPORTED IN THIS VERSION' 
          IERR=1
          RETURN
      ENDIF
CCYYTMP---
C
      WRITE(IUT6,'(A32,I8 )')   'ISTART                      : ',ISTART
      WRITE(IUT6,'(A32,I8 )')   'NTIME                       : ',NTIME
      WRITE(IUT6,'(A32,I8 )')   'IOUT                        : ',IOUT
      WRITE(IUT6,'(A32,I8 )')   'INTFSV                      : ',INTFSV
      WRITE(IUT6,'(A32,1PE13.5 )') 'DSCALE                   : ',DSCALE
      WRITE(IUT6,'(A32,1PE13.5 )') 'VSCALE                   : ',VSCALE
      WRITE(IUT6,'(A32,1PE13.5 )') 'VISCM                    : ',VISCM
      WRITE(IUT6,'(A32,1PE13.5 )') 'RHO0                     : ',RHO0
      WRITE(IUT6,'(A32,I8   )') 'NSAMPL                      : ',NSAMPL
C
      DO 1100 ISAMPL=1,NSAMPL
          IF(LSAMPL(1,ISAMPL).LT.1 .OR. LSAMPL(1,ISAMPL).GT.4) THEN
              WRITE(IUT0,*) ERRMSG
              WRITE(IUT0,*) EREXP1
              IERR = 1
              RETURN
          ENDIF
C
          WRITE(IUT6,600) COMDAT(LSAMPL(1,ISAMPL)) ,
     *                     XSAMPL(ISAMPL),YSAMPL(ISAMPL),ZSAMPL(ISAMPL)
 1100 CONTINUE   
C
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF CUBE       FILE: ',FILECB
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF B.C.       FILE: ',FILEBC
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF INI. FUNC  FILE: ',FILEIF
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF VEL. FUNC  FILE: ',FILEVF
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF HISTORY    FILE: ',FILEHT
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF FINAL FLOW FILE: ',FILEFF
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF AVE FLOW   FILE: ',FILEAV
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF RMS FLOW   FILE: ',FILERM
      WRITE(IUT6,'(A32,A60)')   'FILE NAME OF UNSTEADY   FILE: ',FILEFS
C
      RETURN
 600  FORMAT(  A15 , ' XSMPL =' ,1PE12.5,
     *               ' YSMPL =', 1PE12.5, ' ZSMPL =' ,1PE12.5  )
C
      END
