      SUBROUTINE MKBC02(NP,NG,NC,M1,MBC,LLEVEL,LPOSI,DSCALE,
     *                  NTRIG,XTRIG,YTRIG,ZTRIG,
     *                  MPBOUN,NPBOUN,LPBOUN,QBOUN,
     *                  QCELL,LWORK,IMODQ,EPSTRG,IUT6,IUT0,IERR)
      IMPLICIT NONE
C
C     FUNCTION: MAKE INTERSECT DATA IN EACH CUBE 
C
C
C[INPUT]
      INTEGER*4 NP,NG,NC,M1,MBC,LLEVEL(NC),LPOSI(3,NC),MPBOUN
      REAL*8    DSCALE
      INTEGER*4 NTRIG 
      REAL*4    XTRIG(NTRIG),YTRIG(NTRIG),ZTRIG(NTRIG)
      INTEGER*4 IMODQ
      REAL*8    EPSTRG   
      INTEGER*4 IUT6,IUT0
C
C[INPUT-OUTPUT]
      INTEGER*4 NPBOUN(NC),LPBOUN(5,MPBOUN,NC)
      REAL*4    QBOUN(MPBOUN,NC)
C
C[OUTPUT]
      INTEGER*4 IERR
C
C[WORK]
      INTEGER*4 LWORK(NP,NG+1,NG+1,NG+1)
      REAL*4    QCELL(M1,0:NG+1,0:NG+1,0:NG+1)
C
C[LOCAL]
      INTEGER*4 IC,NDUM
C
      DO 1000 IC=1,NC 
          NDUM=NPBOUN(IC)
          CALL USTSTA(24)
          CALL MKINTR(NP,NG,MBC,M1,LLEVEL(IC),LPOSI(1,IC),DSCALE,
     *                NTRIG,XTRIG,YTRIG,ZTRIG,
     *                MPBOUN,NPBOUN(IC),LPBOUN(1,1,IC),QBOUN(1,IC),
     *                LWORK,QCELL,IMODQ,EPSTRG,IUT6,IUT0,IERR)
          CALL USTEND(24)
          WRITE(IUT6,'(A12,2I8)') 'MKBC02: ', IC,NPBOUN(IC)-NDUM
 1000 CONTINUE
C
C
      RETURN
      END
