      SUBROUTINE ALE_MOVBC1(NP,NPBODY,LPBODY,NPMVB,UMVB,VMVB,WMVB,
     *                      LPCPL,NPCPL,MVEL,NDOF,U000,LWORK,
     *                      WEIGHT,AWRK01,
     *                      ME,NE,N2,IPART,LDOM,NBPDOM,NDOM,
     *                      IPSLF,IPSND,MBPDOM,NUMIP,RX,RY,
     *                      IWRTIM,IUT0,IUT6,IERR) ! DEBUG
C
#ifdef RCAPCPL
      USE RCAPF
#endif
C
      IMPLICIT NONE
C
      INTEGER*4 NP,NPBODY,NPCPL,NPMVB,NDOF
      INTEGER*4 LPBODY(NPBODY),LPCPL(NPCPL)
      REAL*4    UMVB(NPMVB),VMVB(NPMVB),WMVB(NPMVB),U000
      REAL*8    MVEL(NPCPL*3)
      INTEGER*4 ME,NE,N2
      INTEGER*4 IPART,NDOM,MBPDOM,IUT0,IUT6,IERR
      INTEGER*4 LDOM(NDOM),NBPDOM(NDOM),
     *          IPSLF(MBPDOM,NDOM),IPSND(MBPDOM,NDOM),
     *          NUMIP(NP)
      REAL*4    RX(0:N2,ME),RY(0:N2,ME)
C     WORK
      INTEGER*4 IP,IBC,IBP,I,J,K,IDIM,MAXBUF
      INTEGER*4 LWORK(NP)
      REAL*4    WEIGHT(NP),AWRK01(NP*3)
CCHYDEBUG
      INTEGER*4 IWRTIM
CCHYDEBUG
      CHARACTER*60 ERMSGC /' ## SUBROUTINE ALE_MOVBC1: FATAL
     *      ERROR REPORT   ; RETURNED' /
C
      MAXBUF = (N2+1)*NE
C
#ifdef cputime
      IF (IWRTIM.EQ.1) CALL CLTIME('GET_MVEL  :START',IUT6)
#endif
#ifdef RCAPCPL
      CALL RCAPF_GET_MVEL(LPCPL,NPCPL,MVEL,NDOF)
#endif
#ifdef cputime
      IF (IWRTIM.EQ.1) CALL CLTIME('GET_MVEL  :END  ',IUT6)
#endif
C
      DO 100 IP=1,NP
         LWORK(IP)=0
 100  CONTINUE
C
      DO 200 IBP=1,NPBODY
         IP=LPBODY(IBP)
         LWORK(IP)=IBP
 200  CONTINUE
C
      DO 300 IBC=1,NPCPL
         IP=LPCPL(IBC)
         IBP=LWORK(IP)
         I=1+3*(IBC-1)
         J=2+3*(IBC-1)
         K=3+3*(IBC-1)
         UMVB(IBP)=SNGL(MVEL(I))/U000
         VMVB(IBP)=SNGL(MVEL(J))/U000
         WMVB(IBP)=SNGL(MVEL(K))/U000
 300  CONTINUE
C
      DO 400 IP=1,NP
         WEIGHT(IP)=1.E0/(FLOAT(NUMIP(IP))+1.E0)
 400  CONTINUE
C
      DO 500 IP=1,NP*3
         AWRK01(IP)=0.0E0
 500  CONTINUE
C
      DO 600 IBP=1,NPBODY
         IP=LPBODY(IBP)
         AWRK01(IP+NP*0)=WEIGHT(IP)*UMVB(IBP)
         AWRK01(IP+NP*1)=WEIGHT(IP)*VMVB(IBP)
         AWRK01(IP+NP*2)=WEIGHT(IP)*WMVB(IBP)
 600  CONTINUE
C
      IDIM = 3
      CALL DDCOMX(IPART,IDIM,LDOM,NBPDOM,NDOM,IPSLF,IPSND,MBPDOM,
     *     AWRK01,AWRK01(NP+1),AWRK01(NP*2+1),NP,IUT0,IERR,RX,RY,MAXBUF)
      IF(IERR.EQ.1) THEN
         WRITE(IUT0,*)'ERROR CODE REPORTED FROM DDCOMX'
         WRITE(IUT0,*) ERMSGC
         RETURN
      ENDIF
C
      DO 700 IBP=1,NPBODY
         IP=LPBODY(IBP)
         UMVB(IBP)=AWRK01(IP+NP*0)
         VMVB(IBP)=AWRK01(IP+NP*1)
         WMVB(IBP)=AWRK01(IP+NP*2)
 700  CONTINUE
C
      RETURN
      END
