      SUBROUTINE CHKBOX(DOM1,DOM2,ICHECK)
      IMPLICIT NONE
C
C[INPUT] 
      REAL*4    DOM1(6),DOM2(6)
C[OUTPUT] 
      INTEGER*4 ICHECK
C     ICHECK : 0 TWO BOUNDING BOXES ARE NOT OVERLAPPED
C     ICHECK : 1 TWO BOUNDING BOXES ARE     OVERLAPPED
C[LOCAL] 
      REAL*4    XMIN1,XMAX1,DX1
      REAL*4    XMIN2,XMAX2,DX2
      REAL*4    YMIN1,YMAX1,DY1
      REAL*4    YMIN2,YMAX2,DY2
      REAL*4    ZMIN1,ZMAX1,DZ1
      REAL*4    ZMIN2,ZMAX2,DZ2
C
      REAL*4   EPS
      DATA EPS  /1.0E-1/
C
      INTEGER*4 ICHKX,ICHKY,ICHKZ
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
      XMIN1=DOM1(1) 
      XMIN2=DOM2(1) 
      YMIN1=DOM1(2) 
      YMIN2=DOM2(2) 
      ZMIN1=DOM1(3) 
      ZMIN2=DOM2(3) 
      XMAX1=DOM1(4) 
      XMAX2=DOM2(4) 
      YMAX1=DOM1(5) 
      YMAX2=DOM2(5) 
      ZMAX1=DOM1(6) 
      ZMAX2=DOM2(6) 
C
      DX1=XMAX1-XMIN1
      DX2=XMAX2-XMIN2
      DY1=YMAX1-YMIN1
      DY2=YMAX2-YMIN2
      DZ1=ZMAX1-ZMIN1
      DZ2=ZMAX2-ZMIN2
C
      XMIN1=XMIN1-DX1*EPS
      XMIN2=XMIN2-DX2*EPS
      YMIN1=YMIN1-DY1*EPS
      YMIN2=YMIN2-DY2*EPS
      ZMIN1=ZMIN1-DZ1*EPS
      ZMIN2=ZMIN2-DZ2*EPS
C
      XMAX1=XMAX1+DX1*EPS
      XMAX2=XMAX2+DX2*EPS
      YMAX1=YMAX1+DY1*EPS
      YMAX2=YMAX2+DY2*EPS
      ZMAX1=ZMAX1+DZ1*EPS
      ZMAX2=ZMAX2+DZ2*EPS
C
      ICHKX=1
      IF(XMIN1.GT.XMAX2) ICHKX=0      
      IF(XMIN2.GT.XMAX1) ICHKX=0      
C
      ICHKY=1
      IF(YMIN1.GT.YMAX2) ICHKY=0      
      IF(YMIN2.GT.YMAX1) ICHKY=0      
C
      ICHKZ=1
      IF(ZMIN1.GT.ZMAX2) ICHKZ=0      
      IF(ZMIN2.GT.ZMAX1) ICHKZ=0      
C
      ICHECK=ICHKX*ICHKY*ICHKZ
C
      RETURN
      END
C      
