      SUBROUTINE CHKOSB(NP,NPSET,LPSET1,X,Y,Z,
     *                  OSXMIN,OSYMIN,OSZMIN,
     *                  OSXMAX,OSYMAX,OSZMAX,
     *                  IUT0,IUT6,IERR)
      IMPLICIT NONE 
C      
C[INPUT]
      INTEGER*4 NP,NPSET,LPSET1(NPSET) ,IUT0,IUT6
      REAL*4    X(NP),Y(NP),Z(NP)
C      
C[OUTPUT]
      INTEGER*4 IERR
      REAL*4    OSXMIN,OSYMIN,OSZMIN,
     *          OSXMAX,OSYMAX,OSZMAX
C      
C[WORK]
      INTEGER*4  IPB,IP,JMIN,JMAX
      REAL*4     XMIN,YMIN,ZMIN,XMAX,YMAX,ZMAX,DX,DY,DZ 
C
      DATA JMIN /3/
      DATA JMAX /2/
C
      IERR=0
C
      XMIN= 1.0E10
      YMIN= 1.0E10
      ZMIN= 1.0E10
      XMAX=-1.0E10
      YMAX=-1.0E10
      ZMAX=-1.0E10
C
      DO 1000 IPB=1,NPSET
          IP=LPSET1(IPB)
          IF(X(IP).LE.XMIN) XMIN=X(IP)
          IF(Y(IP).LE.YMIN) YMIN=Y(IP)
          IF(Z(IP).LE.ZMIN) ZMIN=Z(IP)
          IF(X(IP).GE.XMAX) XMAX=X(IP)
          IF(Y(IP).GE.YMAX) YMAX=Y(IP)
          IF(Z(IP).GE.ZMAX) ZMAX=Z(IP)
 1000 CONTINUE
C
      WRITE(IUT6,*) 'CHKOSB: XMIN',XMIN
      WRITE(IUT6,*) 'CHKOSB: YMIN',YMIN
      WRITE(IUT6,*) 'CHKOSB: ZMIN',ZMIN
      WRITE(IUT6,*) 'CHKOSB: XMAX',XMAX
      WRITE(IUT6,*) 'CHKOSB: YMAX',YMAX
      WRITE(IUT6,*) 'CHKOSB: ZMAX',ZMAX
C
      CALL DDALLD(XMIN,OSXMIN,JMIN,IUT0,IERR)
      CALL DDALLD(YMIN,OSYMIN,JMIN,IUT0,IERR)
      CALL DDALLD(ZMIN,OSZMIN,JMIN,IUT0,IERR)
      CALL DDALLD(XMAX,OSXMAX,JMAX,IUT0,IERR)
      CALL DDALLD(YMAX,OSYMAX,JMAX,IUT0,IERR)
      CALL DDALLD(ZMAX,OSZMAX,JMAX,IUT0,IERR)
C
      DX=OSXMAX-OSXMIN
      DY=OSYMAX-OSYMIN
      DZ=OSZMAX-OSZMIN
C
      OSXMIN = OSXMIN - DX*0.1E0
      OSYMIN = OSYMIN - DY*0.1E0
      OSZMIN = OSZMIN - DZ*0.1E0
      OSXMAX = OSXMAX + DX*0.1E0
      OSYMAX = OSYMAX + DY*0.1E0
      OSZMAX = OSZMAX + DZ*0.1E0
C
      WRITE(IUT6,*)
      WRITE(IUT6,*) 'CHKOSB: OSXMIN',OSXMIN
      WRITE(IUT6,*) 'CHKOSB: OSYMIN',OSYMIN
      WRITE(IUT6,*) 'CHKOSB: OSZMIN',OSZMIN
      WRITE(IUT6,*) 'CHKOSB: OSXMAX',OSXMAX
      WRITE(IUT6,*) 'CHKOSB: OSYMAX',OSYMAX
      WRITE(IUT6,*) 'CHKOSB: OSZMAX',OSZMAX
C
      RETURN
      END
