      SUBROUTINE DATCNV(IALE,NP,NE,MWRK,
     *                  NPINLT,NPWALL,NPSYMT,NPFREE,NPCCL ,NPBODY,
     *                  NPINT ,NEFFO ,NPFFO ,NPTEMP,NEHSRC,NPHEAT,
     *                  NPSET ,
     *                  LPINLT,LPWALL,LPSYMT,LPFREE,LPCCL1,LPCCL2,
     *                  LPBODY,LPINT1,LEFFO1,LPFFO1,LPTEMP,LEHSRC,
     *                  LPHEAT,LPSET1,
     *                  LEFRM ,IEATTR,IPATTR,IEMEDA,IEPROP,
     *                  X,Y,Z,XD,YD,ZD,U,V,W,PN,P,T,FL,FE,
     *                  UMESH,VMESH,WMESH,UMESH_P,VMESH_P,WMESH_P,
     *                  LPCNV,LECNV,LWRK01,WRK01,IERR,IUT0)
C
      IMPLICIT NONE
C
      INTEGER*4 IALE,NP,NE,MWRK
C     LIST DATA
      INTEGER*4 NPINLT,NPWALL,NPSYMT,NPFREE,NPCCL ,NPBODY,
     *          NPINT, NEFFO, NPFFO ,NPTEMP,NEHSRC,NPHEAT,
     *          NPSET
      INTEGER*4 LPINLT(NPINLT),LPWALL(NPWALL),LPSYMT(NPSYMT),
     *          LPFREE(NPFREE),LPCCL1(NPCCL ),LPCCL2(NPCCL ),
     *          LPBODY(NPBODY),LPINT1(NPINT ),LEFFO1(NEFFO ),
     *          LPFFO1(NPFFO ),LPTEMP(NPTEMP),LEHSRC(NEHSRC),
     *          LPHEAT(NPHEAT),LPSET1(NPSET )
C
C     ATTRIBUTE DATA
      INTEGER*4 LEFRM(NE),IEATTR(NE),IPATTR(NP),IEMEDA(NE),IEPROP(NE)
C
C     FLOW FILED DATA
      REAL*4    X(NP),Y(NP),Z(NP),U(NP),V(NP),W(NP),PN(NP),P(NE),
     *          T(NP),FL(NP),FE(NE),
     *          UMESH(NP),VMESH(NP),WMESH(NP),
     *          UMESH_P(NP),VMESH_P(NP),WMESH_P(NP)
      REAL*8    XD(NP),YD(NP),ZD(NP)
C
C     CONVERSION TABLE
      INTEGER*4 LPCNV(NP),LECNV(NE)
C
C     WORK
      INTEGER*4 IBP,LWRK01(MWRK)
      REAL*4    WRK01 (MWRK)
      INTEGER*4 IERR,IUT0
C
CC
CC    [1] CONVERT LIST DATA
CC
      IF (NPINLT.GE.1) CALL LSTCNV(NP,NPINLT,LPINLT,LPCNV,IERR,IUT0)
      IF (NPWALL.GE.1) CALL LSTCNV(NP,NPWALL,LPWALL,LPCNV,IERR,IUT0)
      IF (NPSYMT.GE.1) CALL LSTCNV(NP,NPSYMT,LPSYMT,LPCNV,IERR,IUT0)
      IF (NPFREE.GE.1) CALL LSTCNV(NP,NPFREE,LPFREE,LPCNV,IERR,IUT0)
      IF (NPCCL .GE.1) CALL LSTCNV(NP,NPCCL ,LPCCL1,LPCNV,IERR,IUT0)
      IF (NPCCL .GE.1) CALL LSTCNV(NP,NPCCL ,LPCCL2,LPCNV,IERR,IUT0)
      IF (NPBODY.GE.1) CALL LSTCNV(NP,NPBODY,LPBODY,LPCNV,IERR,IUT0)
      IF (NPINT .GE.1) CALL LSTCNV(NP,NPINT ,LPINT1,LPCNV,IERR,IUT0)
      IF (NEFFO .GE.1) CALL LSTCNV(NE,NEFFO ,LEFFO1,LECNV,IERR,IUT0)
      IF (NPFFO .GE.1) CALL LSTCNV(NP,NPFFO ,LPFFO1,LPCNV,IERR,IUT0)
      IF (NPTEMP.GE.1) CALL LSTCNV(NP,NPTEMP,LPTEMP,LPCNV,IERR,IUT0)
      IF (NEHSRC.GE.1) CALL LSTCNV(NE,NEHSRC,LEHSRC,LECNV,IERR,IUT0)
      IF (NPHEAT.GE.1) CALL LSTCNV(NP,NPHEAT,LPHEAT,LPCNV,IERR,IUT0)
      IF (NPSET .GE.1) CALL LSTCNV(NP,NPSET ,LPSET1,LPCNV,IERR,IUT0)
CC
CC    [2] CONVERT ATTRIBUTE DATA
CC
      CALL INTCNV(NE,NE,LEFRM ,LECNV,LWRK01,IERR,IUT0)
      CALL INTCNV(NE,NE,IEATTR,LECNV,LWRK01,IERR,IUT0)
      CALL INTCNV(NP,NP,IPATTR,LPCNV,LWRK01,IERR,IUT0)
      CALL INTCNV(NE,NE,IEMEDA,LECNV,LWRK01,IERR,IUT0)
      CALL INTCNV(NE,NE,IEPROP,LECNV,LWRK01,IERR,IUT0)
CC
CC    [3] CONVERT FLOW FILED DATA
CC
      CALL RELCNV(NP,NP,X     ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NP,NP,Y     ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NP,NP,Z     ,LPCNV, WRK01,IERR,IUT0)
      CALL DBLCNV(NP,NP,XD    ,LPCNV,       IERR,IUT0)
      CALL DBLCNV(NP,NP,YD    ,LPCNV,       IERR,IUT0)
      CALL DBLCNV(NP,NP,ZD    ,LPCNV,       IERR,IUT0)
      CALL RELCNV(NP,NP,U     ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NP,NP,V     ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NP,NP,W     ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NP,NP,PN    ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NE,NE,P     ,LECNV, WRK01,IERR,IUT0)
      CALL RELCNV(NP,NP,T     ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NP,NP,FL    ,LPCNV, WRK01,IERR,IUT0)
      CALL RELCNV(NE,NE,FE    ,LECNV, WRK01,IERR,IUT0)
      IF (IALE.GE.1) THEN
         CALL RELCNV(NP,NP,UMESH   ,LPCNV, WRK01,IERR,IUT0)
         CALL RELCNV(NP,NP,VMESH   ,LPCNV, WRK01,IERR,IUT0)
         CALL RELCNV(NP,NP,WMESH   ,LPCNV, WRK01,IERR,IUT0)
         CALL RELCNV(NP,NP,UMESH_P ,LPCNV, WRK01,IERR,IUT0)
         CALL RELCNV(NP,NP,VMESH_P ,LPCNV, WRK01,IERR,IUT0)
         CALL RELCNV(NP,NP,WMESH_P ,LPCNV, WRK01,IERR,IUT0)
      ENDIF
C
      RETURN
      END

