C
C
C     <<<<< SUBROUTINE TO SET MOVING BOUNDARY NODE LIST FOR ALE >>>>>
C
C
      SUBROUTINE MVBOUN(MB,NP,
     *                 NPINLT,NPFREE,NPWALL,NPSYMT,NPCCL,NPBODY,
     *                 NPSETR,NPMVB,
     *                 LPINLT,LPFREE,LPWALL,LPSYMT,LPCCL1,LPCCL2,LPBODY,
     *                 LPSET1,LPMVB,
     *                 UMVB,VMVB,WMVB,LWRK01,IUT6,IUT0,IERR)
C
      IMPLICIT NONE
C[INPUT]
      INTEGER*4 MB,NP
      INTEGER*4 NPINLT,NPFREE,NPWALL,NPSYMT,NPCCL,NPBODY,NPSETR
      INTEGER*4 LPINLT(NPINLT),LPFREE(NPFREE),LPWALL(NPWALL),
     *          LPSYMT(NPSYMT),LPCCL1(NPCCL ),LPCCL2(NPCCL ),
     *          LPBODY(NPBODY),LPSET1(NPSETR)
      INTEGER*4 IUT6,IUT0
C
C[OUTPUT]
      INTEGER*4 NPMVB
      INTEGER*4 LPMVB(3,MB)
      REAL*4    UMVB(MB),VMVB(MB),WMVB(MB)
      INTEGER*4 IERR
C
C[INPUT(WORK)]
      INTEGER*4 LWRK01(NP)
C
C[LOCAL]
      INTEGER*4 IP,IBP
      CHARACTER*60 ERMSG1
     * / ' SUB. MVBOUN: NUM. OF MOV. B.C. NODES EXCEEDED LIMIT OF ' /
      CHARACTER*10 BLANK / ' ' /
C
C
C
      WRITE(IUT6,*) BLANK
      WRITE(IUT6,*) ' ** SETTING MOVING BOUNDARY DATA FOR ALE **'
C
      DO 1000 IP=1,NP
         LWRK01(IP)=0
 1000 CONTINUE
C
      NPMVB=0
      DO 1100 IBP = 1 , NPBODY
         IF (LWRK01(LPBODY(IBP)).EQ.1) GOTO 1100
         LWRK01(LPBODY(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPBODY(IBP)
         LPMVB(2,NPMVB) = LPBODY(IBP)
         LPMVB(3,NPMVB) = LPBODY(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1100 CONTINUE
      DO 1200 IBP = 1 , NPINLT
         IF (LWRK01(LPINLT(IBP)).EQ.1) GOTO 1200
         LWRK01(LPINLT(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPINLT(IBP)
         LPMVB(2,NPMVB) = LPINLT(IBP)
         LPMVB(3,NPMVB) = LPINLT(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1200 CONTINUE
      DO 1300 IBP = 1 , NPFREE
         IF (LWRK01(LPFREE(IBP)).EQ.1) GOTO 1300
         LWRK01(LPFREE(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPFREE(IBP)
         LPMVB(2,NPMVB) = LPFREE(IBP)
         LPMVB(3,NPMVB) = LPFREE(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1300 CONTINUE
      DO 1400 IBP = 1 , NPWALL
         IF (LWRK01(LPWALL(IBP)).EQ.1) GOTO 1400
         LWRK01(LPWALL(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPWALL(IBP)
         LPMVB(2,NPMVB) = LPWALL(IBP)
         LPMVB(3,NPMVB) = LPWALL(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1400 CONTINUE
      DO 1500 IBP = 1 , NPSYMT
         IF (LWRK01(LPSYMT(IBP)).EQ.1) GOTO 1500
         LWRK01(LPSYMT(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPSYMT(IBP)
         LPMVB(2,NPMVB) = LPSYMT(IBP)
         LPMVB(3,NPMVB) = LPSYMT(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1500 CONTINUE
      DO 1600 IBP = 1 , NPCCL
         IF (LWRK01(LPCCL1(IBP)).EQ.1) GOTO 1600
         LWRK01(LPCCL1(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPCCL1(IBP)
         LPMVB(2,NPMVB) = LPCCL1(IBP)
         LPMVB(3,NPMVB) = LPCCL1(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1600 CONTINUE
      DO 1700 IBP = 1 , NPCCL
         IF (LWRK01(LPCCL2(IBP)).EQ.1) GOTO 1700
         LWRK01(LPCCL2(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPCCL2(IBP)
         LPMVB(2,NPMVB) = LPCCL2(IBP)
         LPMVB(3,NPMVB) = LPCCL2(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1700 CONTINUE
      DO 1800 IBP = 1 , NPSETR
         IF (LWRK01(LPSET1(IBP)).EQ.1) GOTO 1800
         LWRK01(LPSET1(IBP))=1
         NPMVB=NPMVB+1
         IF (NPMVB.GT.MB) GOTO 9999
         LPMVB(1,NPMVB) = LPSET1(IBP)
         LPMVB(2,NPMVB) = LPSET1(IBP)
         LPMVB(3,NPMVB) = LPSET1(IBP)
         UMVB(NPMVB) = 0.E0
         VMVB(NPMVB) = 0.E0
         WMVB(NPMVB) = 0.E0
 1800 CONTINUE
C
      WRITE(IUT6,*) ' DONE!'
      RETURN
C
 9999 CONTINUE
      WRITE(IUT0,*) BLANK
      WRITE(IUT0,*) ERMSG1,MB
      IERR=1
C
      RETURN
      END
