      SUBROUTINE RDSURF(IUT0,IUT6,IUTSF,FILESF,
     *     MCOMFL,NCOMFL,CCOMFL,MCOMST,NCOMST,CCOMST,
     *     MSURFD,MSURFS,NSURFD,NSURFS,XSURFD,YSURFD,ZSURFD,
     *     XMINSF,YMINSF,ZMINSF,XMAXSF,YMAXSF,ZMAXSF)
C
      IMPLICIT NONE
      INTEGER ISURF,IPSURF
      INTEGER*4 IUT0,IUT6,IUTSF,NX,NY,NZ,
     *     MCOMFL,NCOMFL,MCOMST,NCOMST,
     *     MSURFD,MSURFS
      REAL*4 XMINSF(MSURFS),YMINSF(MSURFS),ZMINSF(MSURFS),
     *     XMAXSF(MSURFS),YMAXSF(MSURFS),ZMAXSF(MSURFS),
     *     XSURFD(MSURFD,MSURFS),YSURFD(MSURFD,MSURFS),
     *     ZSURFD(MSURFD,MSURFS),
     *     XMIN,YMIN,ZMIN,XMAX,YMAX,ZMAX,
     *     XBUF,YBUF,ZBUF
      CHARACTER*60 CCOMFL(MCOMFL),CCOMST(MCOMFL)
      CHARACTER*20 FILESF
      INTEGER*4 NSURFD(MSURFS),NSURFS
C
      OPEN(IUTSF,FILE=FILESF)
      READ(IUTSF,*) NSURFS
      WRITE(IUT6,*) "READING ", NSURFS, "SURFACE DOMAINS"
C
      DO 100 ISURF=1, NSURFS
         READ(IUTSF,*) NX,NY
         WRITE(IUT6,*) "SURFACE DOMAIN", ISURF
         WRITE(IUT6,*) "    ", NX, " x ", NY
         NSURFD(ISURF)=NX*NY
 100  CONTINUE
C
      DO 200 ISURF=1, NSURFS
         XMIN=1E+10
         YMIN=1E+10
         ZMIN=1E+10
         XMAX=-1E+10
         YMAX=-1E+10
         ZMAX=-1E+10
         DO 210 IPSURF=1, NSURFD(ISURF)
            READ(IUTSF,*) XBUF, YBUF, ZBUF
C
            IF(XMIN.GT.XBUF) XMIN=XBUF
            IF(XMAX.LT.XBUF) XMAX=XBUF
            XSURFD(IPSURF,ISURF)=XBUF
C
            IF(YMIN.GT.YBUF) YMIN=YBUF
            IF(YMAX.LT.YBUF) YMAX=YBUF
            YSURFD(IPSURF,ISURF)=YBUF
C
            IF(ZMIN.GT.ZBUF) ZMIN=ZBUF
            IF(ZMAX.LT.ZBUF) ZMAX=ZBUF
            ZSURFD(IPSURF,ISURF)=ZBUF
 210     CONTINUE
         XMAXSF(ISURF)=XMAX
         XMINSF(ISURF)=XMIN
         YMAXSF(ISURF)=YMAX
         YMINSF(ISURF)=YMIN
         ZMAXSF(ISURF)=ZMAX
         ZMINSF(ISURF)=ZMIN
         WRITE(IUT6,*) "READ ", NSURFD(ISURF), " SURFACE-DOMAIN FACES"
         WRITE(IUT6,*) "BOUNDING BOX: ", XMAX, YMAX, ZMAX
         WRITE(IUT6,*) "BOUNDING BOX: ", XMIN, YMIN, ZMIN
 200  CONTINUE
C
      CLOSE(IUTSF)
C
      RETURN 
      END
