      SUBROUTINE SLVALE(MCOLOR,MCPART,NCOLOR,NCPART,LLOOP,
     *                  MELM,ME,NELM,NE,NP,N1,N2,NEX,NS,NSP,N2D,NCRS,
     *                  LOCAL,NODE,LTAB,NPP,IPCRS,
     *                  XD,YD,ZD,X,Y,Z,
     *                  UMESH,VMESH,WMESH,UMESH_P,VMESH_P,WMESH_P,EJ,
     *                  NPBODY,NPMVB,LPBODY,LPMVB,UMVB,VMVB,WMVB,
     *                  IALE,NMAXA,NMODE,NITRA,NLYNG,EPSA,EPSREA,RESA,
     *                  STPWR,AOBJ,TOBJ,EYNG,IFLCPL,ITIME,ISTART,
     *                  U000,DT,TIME,
     *                  IPART,MDOM,NDOM,MBPDOM,LDOM,NBPDOM,IPSLF,IPSND,
     *                  NUMIP,
     *                  MGAUSS,IGAUSH,IGAUSW,IGAUSP,IGAUST,
     *                  SNI,DNXI,DNYI,DNZI,
     *                  SN,DNXYZ,E,EX,EY,EZ,EXX,EYY,EZZ,EXY,EYZ,EXZ,
     *                  DELTA,
     *                  EAP1,EAP2,EAP3,EBP,MEP,MP,IENP,JENP,NEP,
     *                  NEBODY,NEHEAT,NSTET,NSPRD,NSWED,NSHEX,
     *                  LEBODY,LEHEAT,SBODY,DXBODY,DYBODY,DZBODY,SHEAT,
     *                  IFILTR,FILTER,IMODEL,JPRESS,NEWALL,LEWALL,
     *                  NEAR,
     *                  DSNEAR,NAVDYN,NPFREE,NPSLD2,LPFREE,LPSLD2,
     *                  GAMDYN,APRS,APRS0,ATEST0,AAVER0,ATESPC,AAVEPC,
#ifdef RCAPCPL
     *                  NPCPL,NDOF,LPCPL,BFCPL,XPCPL,YPCPL,ZPCPL,
#endif
     *                  MPWLAD,NPWALL,NEWLAD,NPWLAD,LPWALL,XNWALL,
     *                  YNWALL,ZNWALL,LEWLAD,LPWLAE,LPWLAD,DPWLAD,
     *                  MAXBUF,MWRK,LWRK01,LWRK02,LWRK03,LEWRK,
     *                  RX,RY,WRKN,
     *                  WRK01,WRK02,WRK03,WRK04,WRK05,WRK06,
     *                  DWRK01,DWRK02,DWRK03,DWRK04,DWRK05,
     *                  AWRK01,AWRK02,AWRK03,AWRK04,AWRK05,AWRK06,
     *                  AWRK07,AWRK08,AWRK09,AWRK10,ACRS2,IWRTIM,
#ifdef cputime
     *                  DTALE,TBUF7,TBUF8,TBUF9,
#endif
     *                  MRSALE,IALEDB,ISTEP,IUTAL,IUT6,IUT0,IERR)
C
      IMPLICIT NONE
C
      INTEGER*4 MCOLOR,MCPART
      INTEGER*4 NCOLOR,NCPART,LLOOP
      INTEGER*4 MELM,ME,NELM,NE,NP,N1,N2,NEX,NS,NSP,N2D,NCRS
      INTEGER*4 LOCAL,NODE,LTAB,NPP,IPCRS
      REAL*8    XD(NP),YD(NP),ZD(NP)
      REAL*4    X(NP),Y(NP),Z(NP),
     *          UMESH,VMESH,WMESH,UMESH_P,VMESH_P,WMESH_P,EJ
      INTEGER*4 NPBODY,NPMVB,LPBODY,LPMVB
      REAL*4    UMVB,VMVB,WMVB
C
      INTEGER*4 IALE,NMAXA,NMODE,NITRA,NLYNG
      REAL*4    EPSA,EPSREA,RESA,STPWR,AOBJ,TOBJ,EYNG
CCHY_TMP
      INTEGER*4 MRSALE,IALEDB,ISTEP,IUTAL
CCHY_TMP
      INTEGER*4 IFLCPL,ITIME,ISTART
      REAL*4    U000,DT,TIME
      INTEGER*4 IPART,MDOM,NDOM,MBPDOM
      INTEGER*4 LDOM,NBPDOM,IPSLF,IPSND,NUMIP
C
C     [INTEGRAL ELEMENT MATRICES]
      INTEGER*4 MGAUSS,IGAUSH,IGAUSW,IGAUSP,IGAUST
      REAL*4    SNI,DNXI,DNYI,DNZI,
     *          SN,DNXYZ,E,EX,EY,EZ,EXX,EYY,EZZ,
     *          EXY,EYZ,EXZ,DELTA
      REAL*4    EAP1,EAP2,EAP3,EBP
      INTEGER*4 IENP,JENP,NEP,MEP,MP
      DIMENSION EAP1(N2,MEP,NP),EAP2(3,N2,MEP,NP),EAP3(6,N2,MEP,NP)
      DIMENSION EBP(3,N2,MEP,NP)
      DIMENSION IENP(MEP,MP),JENP(MEP,MP),NEP(MP)
C
C     [INTEGRAL ELEMENT VECTORS NEEDED]
      INTEGER*4 NEBODY,NEHEAT,NSTET,NSPRD,NSWED,NSHEX
      INTEGER*4 LEBODY,LEHEAT
      REAL*4    SBODY,DXBODY,DYBODY,DZBODY,SHEAT
C
C     [COMPUTE ELEMENT FILTER WIDTH]
      INTEGER*4 IFILTR
      REAL*4    FILTER
C
C     [SEARCH NEAREST WALL SURFACE FOR ALL ELEMENTS]
      INTEGER*4 IMODEL,JPRESS,NEWALL
      INTEGER*4 LEWALL,NEAR,DSNEAR
C
C     [CAL. L.H.S. FOR PRS. EQ. AND DSM]
      INTEGER*4 NAVDYN,NPFREE,NPSLD2
      INTEGER*4 LPFREE,LPSLD2
      REAL*4    GAMDYN,APRS,APRS0,ATEST0,AAVER0,ATESPC,AAVEPC
C
#ifdef RCAPCPL
C     [REVOCAP COUPLER: OBTAIN NODE LIST]
      INTEGER*4 NPCPL,NDOF,LPCPL
      REAL*8    BFCPL
      REAL*4    XPCPL,YPCPL,ZPCPL
#endif
C
C     [SEARCHING WALL ADJACENT NODES]
      INTEGER*4 MPWLAD,NPWALL,NEWLAD,NPWLAD
      INTEGER*4 LPWALL,XNWALL,YNWALL,ZNWALL,
     *          LEWLAD,LPWLAE,LPWLAD,DPWLAD
C
C     [WORK]
      INTEGER*4 MAXBUF,MWRK
      INTEGER*4 LWRK01,LWRK02,LWRK03,LEWRK
      REAL*4    RX,RY,WRKN,
     *          WRK01,WRK02,WRK03,WRK04,WRK05,WRK06,
     *          AWRK01,AWRK02,AWRK03,AWRK04,AWRK05,AWRK06,
     *          AWRK07,AWRK08,AWRK09,AWRK10,ACRS2
      REAL*8    DWRK01,DWRK02,DWRK03,DWRK04,DWRK05
C
      INTEGER*4 IWRTIM
#ifdef cputime
      REAL*4    DTALE(8),TBUF7,TBUF8,TBUF9
#endif
      INTEGER*4 IUT6,IUT0,IERR
C
C     [LOCAL]
      INTEGER*4 IP,IERRA
      CHARACTER*10 BLANK / ' ' /
      CHARACTER*60 ERMSGC
     */' ## SUBROUTINE SLVALE: FATAL ERROR REPORT   ; RETURNED' /
C
C
C
#ifdef cputime
      include 'mpif.h'
C     CALL CPU_TIME( TBUF7 )
      TBUF7 = MPI_WTIME()
      IF (IWRTIM.EQ.1) CALL CLTIME('ALE EQ.   :START',IUT6)
#endif
C
      IF (IFLCPL.GE.1.AND.IALE.EQ.1) THEN
#ifdef RCAPCPL
         CALL ALE_MOVBC1(NP,NPBODY,LPBODY,NPMVB,UMVB,VMVB,WMVB,
     *                   LPCPL,NPCPL,BFCPL,NDOF,U000,LWRK01,
     *                   WRK01,AWRK01,
     *                   ME,NE,IPART,N2,LDOM,NBPDOM,NDOM,
     *                   IPSLF,IPSND,MBPDOM,NUMIP,RX,RY,
     *                   IWRTIM,IUT0,IUT6,IERR)
#endif 
      ELSE IF (IALE.EQ.2) THEN
         CALL ALE_MOVBC2(NP,NPBODY,LPBODY,NPMVB,UMVB,VMVB,WMVB,
     *                   NMODE,AOBJ,TOBJ,TIME,DT,X,Y,Z)
      ELSE IF (IALE.EQ.3) THEN
         CALL ALE_MOVBC3
      ENDIF
      CALL ERCHK2(IUT6,IPART,1,IERR,IERRA)
      IF(IERRA.NE.0) THEN
         WRITE(IUT0,*) BLANK
         WRITE(IUT0,*) ERMSGC
         GOTO 9999
      ENDIF
C
      CALL ALE_CALYNG(NP,NE,NPMVB,LPMVB,
     *                STPWR,EJ,DELTA,
     *                NLYNG,EYNG,ME,N2,NODE,NPBODY,LPBODY,
     *                LWRK01,LWRK02,WRK01,
     *                IPART,NDOM,MBPDOM,LDOM,NBPDOM,
     *                IPSLF,IPSND,RX,RY,MAXBUF,IUT0,IERR)
      CALL ERCHK2(IUT6,IPART,1,IERR,IERRA)
      IF(IERRA.NE.0) THEN
         WRITE(IUT0,*) BLANK
         WRITE(IUT0,*) ERMSGC
         GOTO 9999
      ENDIF
C
CCHY_TMP
      IF (IALEDB.GE.1.AND.IPART.EQ.1) WRITE(IUTAL,*)'STEP',ISTEP
CCHY_TMP

      CALL ALE_CALMOV(MCOLOR,MCPART,NCOLOR,NCPART,LLOOP,
     *                NEX,EPSA,EPSREA,NMAXA,X,Y,Z,
     *                NELM,EAP3,EBP,MEP,MP,IENP,JENP,NEP,
     *                NODE,ME,NE,NP,ME,EJ,DT,
     *                NCRS,N1,N2,LTAB,NPP,IPCRS,ACRS2,
     *                NPMVB,LPMVB,UMVB,VMVB,WMVB,
     *                UMESH,VMESH,WMESH,
     *                UMESH_P,VMESH_P,WMESH_P,ITIME,ISTART,
     *                IPART,LDOM,NBPDOM,NDOM,
     *                IPSLF,IPSND,MBPDOM,NUMIP,
     *                NITRA,RESA,RX,RY,WRK01,AWRK01,AWRK02,
     *                AWRK03,AWRK04,AWRK05,AWRK06,AWRK07,
     *                AWRK08,AWRK09,AWRK10,LWRK01,LWRK02,LWRK03,
     *                MRSALE,IALEDB,IUTAL,IUT0,IUT6,IERR )
      CALL ERCHK2(IUT6,IPART,1,IERR,IERRA)
      IF(IERRA.NE.0) THEN
         WRITE(IUT0,*) BLANK
         WRITE(IUT0,*) ERMSGC
         GOTO 9999
      ENDIF
C
      DO 1000 IP=1, NP
         XD(IP)=DBLE(X(IP))
         YD(IP)=DBLE(Y(IP))
         ZD(IP)=DBLE(Z(IP))
 1000 CONTINUE
CCHY_TMP
      IF (IALEDB.GE.1.AND.IPART.EQ.1) THEN
         IF (MOD(ITIME,50).EQ.0) THEN
            CLOSE(IUTAL)
            OPEN(IUTAL,FILE="ale_res.log")
         ENDIF
      ENDIF
CCHY_TMP
C
#ifdef cputime
      IF (IWRTIM.EQ.1) CALL CLTIME('ALE EQ.   :END  ',IUT6)
C     CALL CPU_TIME( TBUF8 )
      TBUF8 = MPI_WTIME()
      IF (IWRTIM.EQ.1) CALL CLTIME('UPDT MESH :START',IUT6)
#endif
C
      CALL ALE_MSHINF(MCOLOR,MCPART,NCOLOR,NCPART,LLOOP,
     *                N1,N2,NE,NP,NEX,NS,NSP,N2D,NELM,LOCAL,NODE,
     *                X,Y,Z,XD,YD,ZD,
     *                IPART,MDOM,NDOM,LDOM,NBPDOM,MBPDOM,IPSLF,IPSND,
     *                MGAUSS,IGAUSH,IGAUSW,IGAUSP,IGAUST,MELM,ME,
     *                SNI,DNXI,DNYI,DNZI,SN,DNXYZ,
     *                E,EX,EY,EZ,EXX,EYY,EZZ,EXY,EYZ,EXZ,DELTA,
     *                EAP1,EAP2,EAP3,EBP,MEP,MP,IENP,JENP,NEP,
     *                NEBODY,NEHEAT,NSTET,NSPRD,NSWED,NSHEX,
     *                LEBODY,LEHEAT,SBODY,DXBODY,DYBODY,DZBODY,SHEAT,
     *                IFILTR,FILTER,
     *                IMODEL,JPRESS,NEWALL,LEWALL,NEAR,DSNEAR,
     *                NCRS,NAVDYN,NPFREE,NPSLD2,
     *                LTAB,LPFREE,LPSLD2,GAMDYN,APRS,APRS0,ATEST0,
     *                AAVER0,ATESPC,AAVEPC,
#ifdef RCAPCPL
     *                NPCPL,LPCPL,XPCPL,YPCPL,ZPCPL,
#endif
     *                MPWLAD,NPWALL,NEWLAD,NPWLAD,LPWALL,
     *                XNWALL,YNWALL,ZNWALL,LEWLAD,LPWLAE,LPWLAD,DPWLAD,
     *                MAXBUF,MWRK,RX,RY,WRKN,WRK01,WRK02,WRK03,WRK04,
     *                WRK05,WRK06,DWRK01,DWRK02,DWRK03,DWRK04,DWRK05,
     *                LWRK01,LWRK02,LEWRK,IWRTIM,
#ifdef cputime
     *                DTALE,IUT6,IUT0,IERR)
#else
     *                IUT6,IUT0,IERR)
#endif
      CALL ERCHK2(IUT6,IPART,1,IERR,IERRA)
      IF(IERRA.NE.0) THEN
         WRITE(IUT0,*) BLANK
         WRITE(IUT0,*) ERMSGC
         GOTO 9999
      ENDIF
C
#ifdef cputime
      IF (IWRTIM.EQ.1) CALL CLTIME('UPDT MESH :END  ',IUT6)
C     CALL CPU_TIME( TBUF9 )
      TBUF9 = MPI_WTIME()
#endif
C
 9999 CONTINUE
C
      RETURN
      END
