      SUBROUTINE DDMID0(LPMID1,LPMID2,LPMID3,NPMID,MPT,MDOM,IUT0,
     *                  NGAT,LGAT,NPTGAT,IPMID,IPGAT,
     *                  NSCT,LSCT,NPTSCT,IEMID,IPSCT,IERR)
      IMPLICIT NONE
      INTEGER*4 NPMID,MPT,MDOM,NGAT,NSCT,IUT0,IERR
      INTEGER*4 LPMID1(NPMID),LPMID2(NPMID),LPMID3(NPMID),
     *          LGAT(MDOM),NPTGAT(MDOM),IPMID(MPT,MDOM),IPGAT(MPT,MDOM),
     *          LSCT(MDOM),NPTSCT(MDOM),IEMID(MPT,MDOM),IPSCT(MPT,MDOM)
C
      INTEGER*4 IDOM,NDUM,IBP,IFNEW,ICHK
C
      CHARACTER*60 ERMSGB
     & / ' ## SUBROUTINE DDMID0: FATAL     ERROR OCCURRENCE; RETURNED' /
      CHARACTER*60 EREXP1
     & / ' DIMENSION SIZE OF PASSED LIST ARRAYS IS NOT SUFFICIENT    ' /
C
C
      IERR = 0
C
C
      RETURN
      END
C
