      SUBROUTINE DDMID2(IMODE,MPT,MDOM,NPMID,MAXBUF,
     *                  NPGAT,LPGAT,VGAT,
     *                  NPSCT,LESCT,CSCT,VSCT,
     *                  NGAT,LGAT,NPTGAT,IPMID,IPGAT,
     *                  NSCT,LSCT,NPTSCT,IEMID,IPSCT,
     *                  BUFRCV,BUFSND,IUT0,IERR)
      IMPLICIT NONE
      INTEGER*4 IMODE,
     *          MPT,MDOM,NPMID,MAXBUF,NGAT,NSCT,NPGAT,NPSCT,IUT0,IERR
      INTEGER*4 LGAT(MDOM),NPTGAT(MDOM),IPMID(MPT,MDOM),IPGAT(MPT,MDOM),
     *          LSCT(MDOM),NPTSCT(MDOM),IEMID(MPT,MDOM),IPSCT(MPT,MDOM)
C
      INTEGER*4 LPGAT(NPMID),LESCT(NPMID)
      REAL*4    VGAT(NPMID),VSCT(NPMID),CSCT(3,NPMID)
C
      REAL*4    BUFRCV(MAXBUF),BUFSND(MAXBUF)
      INTEGER*4 NSTART,IDOM,IPT,IRECV,ISEND,MSGTYP,MSGLEN
C
      CHARACTER*60 ERMSGB
     & / ' ## SUBROUTINE DDMID1: FATAL     ERROR OCCURRENCE; RETURNED' /
      CHARACTER*60 EREXP1
     & / ' DIMENSION SIZE OF INTERNAL      ARRAYS IS NOT SUFFICIENT  ' /
      CHARACTER*60 EREXP2
     & / ' DIMENSION SIZE OF PASSED BUFFER ARRAYS IS NOT SUFFICIENT  ' /
      CHARACTER*60 EREXP3
     & / ' RECEIVED NODE NUMBER IS OUT OF THE GLOBAL NODE NUMBER     ' /
C
C
      RETURN
      END
