      SUBROUTINE DDMAXI(IBUF,IMAX,IERR)
      IMPLICIT NONE
C
      INCLUDE 'mpif.h'
C
      INTEGER*4 IBUF,IMAX,IERR
C
      CALL MPI_ALLREDUCE(IBUF,IMAX,1,MPI_INTEGER,MPI_MAX,
     *                   MPI_COMM_WORLD,IERR)
C
      RETURN
      END
C
      SUBROUTINE DDSET4(IPART,NPART,NUM,LDATA,IERR)
      IMPLICIT NONE
      INTEGER*4 IPART,NPART,NUM,LDATA(NUM,NPART),IERR
      INTEGER*4 LBUF(NUM),I
C
      INCLUDE 'mpif.h'
C
      DO 1000 I=1,NUM 
          LBUF(I)=LDATA(I,IPART)
 1000 CONTINUE   
C
      CALL MPI_ALLGATHER(LBUF, NUM,MPI_INTEGER,
     *                   LDATA,NUM,MPI_INTEGER,
     *                   MPI_COMM_WORLD,IERR) 
C
      RETURN
      END
C
      SUBROUTINE DDSET5(IPART,MBPDOM,
     *                  NDOMS,LDOMS,NBDOMS,LBUFS,
     *                  NDOMR,LDOMR,NBDOMR,LBUFR,IERR)
      IMPLICIT NONE
      INTEGER*4 IPART,MBPDOM,IERR,
     *          NDOMS               ,NDOMR               , 
     *          LDOMS (       NDOMS),LDOMR (       NDOMR),
     *          NBDOMS(       NDOMS),NBDOMR(       NDOMR),
     *          LBUFS (MBPDOM,NDOMS),LBUFR (MBPDOM,NDOMR)
C
      INTEGER*4 NCOM,ISLFR,ISLFS,IDOMR,IDOMS,I
      DATA NCOM  /0/
      DATA ISLFR /0/
      DATA ISLFS /0/
C
      INCLUDE 'mpif.h'
C
      INTEGER*4 MAXDOM,MSGTYP,MSGLEN,IRECV,ISEND
      PARAMETER (MAXDOM=30000)
      INTEGER*4 MSGIDS(MAXDOM),MSGSTS(MPI_STATUS_SIZE,MAXDOM)
      DATA MSGTYP /1/
C
      NCOM=0 
C
      DO 1000 IDOMR=1,NDOMR
          IF(IPART.EQ.LDOMR(IDOMR)) THEN
              ISLFR=IDOMR
              GOTO 1000
          ENDIF 
          MSGLEN=NBDOMR(IDOMR)
          IRECV =LDOMR(IDOMR)-1
          NCOM=NCOM+1
          CALL MPI_IRECV(LBUFR(1,IDOMR),MSGLEN,MPI_REAL,IRECV,MSGTYP,
     *                   MPI_COMM_WORLD,MSGIDS(NCOM),IERR)
 1000 CONTINUE
C
      DO 1100 IDOMS=1,NDOMS
          IF(IPART.EQ.LDOMS(IDOMS)) THEN
              ISLFS=IDOMS     
              GOTO 1100
          ENDIF 
          MSGLEN=NBDOMS(IDOMS)
          ISEND =LDOMS(IDOMS)-1
          NCOM=NCOM+1
          CALL MPI_ISEND(LBUFS(1,IDOMS),MSGLEN,MPI_REAL,ISEND,MSGTYP,
     *                   MPI_COMM_WORLD,MSGIDS(NCOM),IERR)
 1100 CONTINUE
C
      CALL MPI_WAITALL(NCOM,MSGIDS,MSGSTS,IERR)
C
      IF(ISLFR.EQ.0) RETURN
C
      DO 2000 I=1,NBDOMS(ISLFS)
          LBUFR(I,ISLFR)=LBUFS(I,ISLFS)
 2000 CONTINUE   
C
      RETURN
      END
      SUBROUTINE DDSET6(IPART,MCOMM,
     *                  NDOMS,LDOMS,NBDOMS,LISTS,LBUFS,
     *                  NDOMR,LDOMR,NBDOMR,LISTR,LBUFR,IERR)
      IMPLICIT NONE
      INTEGER*4 IPART,MBPDOM,IERR,
     *          MCOMM,NDOMS,NDOMR, 
     *          LDOMS (NDOMS),LDOMR (NDOMR),
     *          NBDOMS(NDOMS),NBDOMR(NDOMR),
     *          LISTS (NDOMS),LISTR (NDOMR),
     *          LBUFS (MCOMM),LBUFR (MCOMM)
C
      INTEGER*4 NCOM,ISLFR,ISLFS,IDOMR,IDOMS,I
      DATA NCOM  /0/
      DATA ISLFR /0/
      DATA ISLFS /0/
C
      INCLUDE 'mpif.h'
C
      INTEGER*4 MAXDOM,MSGTYP,MSGLEN,IRECV,ISEND
      PARAMETER (MAXDOM=30000)
      INTEGER*4 MSGIDS(MAXDOM),MSGSTS(MPI_STATUS_SIZE,MAXDOM)
      DATA MSGTYP /1/
C
      NCOM=0 
C
      DO 1000 IDOMR=1,NDOMR
          IF(IPART.EQ.LDOMR(IDOMR)) THEN
              ISLFR=IDOMR
              GOTO 1000
          ENDIF 
          MSGLEN=NBDOMR(IDOMR)
          IRECV =LDOMR(IDOMR)-1
          NCOM=NCOM+1
          CALL MPI_IRECV(LBUFR(LISTR(IDOMR)),MSGLEN,MPI_REAL,IRECV,
     *                   MSGTYP,MPI_COMM_WORLD,MSGIDS(NCOM),IERR)
 1000 CONTINUE
C
      DO 1100 IDOMS=1,NDOMS
          IF(IPART.EQ.LDOMS(IDOMS)) THEN
              ISLFS=IDOMS     
              GOTO 1100
          ENDIF 
          MSGLEN=NBDOMS(IDOMS)
          ISEND =LDOMS(IDOMS)-1
          NCOM=NCOM+1
          CALL MPI_ISEND(LBUFS(LISTS(IDOMS)),MSGLEN,MPI_REAL,ISEND,
     *                   MSGTYP,MPI_COMM_WORLD,MSGIDS(NCOM),IERR)
 1100 CONTINUE
C
      CALL MPI_WAITALL(NCOM,MSGIDS,MSGSTS,IERR)
C
      IF(ISLFR.EQ.0) RETURN
C
      DO 2000 I=1,NBDOMS(ISLFS)
          LBUFR(LISTR(ISLFR)+I-1)=LBUFS(LISTS(ISLFS)+I-1)
 2000 CONTINUE   
C
      RETURN
      END
C
