! Obtain tofu-coordinate
! 5.1.2.1 FJMPI_TOPOLOGY_GET_COORDS
SUBROUTINE TOFUCD(IPART,LCLOGI,LCTOFU)
    USE mpi_f08_ext
    IMPLICIT NONE
!INPUT
    INTEGER*4 IPART
!OUTPUT
    INTEGER*4 LCLOGI(6),LCTOFU(6)
!LOCAL
    INTEGER*4 MYRANK,IERR,MAXDIMS,VIEW


    LCLOGI(:)=0
    LCTOFU(:)=0
    MYRANK=IPART-1
    
    ! FOR LOGICAL COORDINATE
    VIEW = FJMPI_LOGICAL
    MAXDIMS = 3
    CALL FJMPI_Topology_get_coords(MPI_COMM_WORLD, MYRANK, VIEW, MAXDIMS, LCLOGI, IERR)

    ! FOR TOFU COORDINATE
    VIEW = FJMPI_TOFU_SYS
    MAXDIMS = 6
    CALL FJMPI_Topology_get_coords(MPI_COMM_WORLD, MYRANK, VIEW, MAXDIMS, LCTOFU, IERR)

    RETURN
END SUBROUTINE TOFUCD

